# Sequence vs. Numpy Array

In [103]:
x = [0, 1, 2]*2            ; print(x)
x = np.array([0, 1, 2])*2 ; print(x)

[0, 1, 2, 0, 1, 2]
[0 2 4]


# Array Creation 

In [27]:
import numpy as np

a = np.empty(3)         ; print(a)
a = np.zeros(3)         ; print(a)
a = np.ones(3)          ; print(a)
a = np.full(3, 2.2)     ; print(a)
a = np.full(3, 2)       ; print(a)
a = np.arange(3)        ; print(a)
a = np.array([0, 1, 2]) ; print(a)

[0.e+000 5.e-324 1.e-323]
[0. 0. 0.]
[1. 1. 1.]
[2.2 2.2 2.2]
[2 2 2]
[0 1 2]
[0 1 2]


# Same Data Type

In [28]:
import numpy as np

a = np.empty(3)
print(a)
a[0] = int(1)
print(a)

[1.e+000 5.e-324 1.e-323]
[1.e+000 5.e-324 1.e-323]


In [29]:
import numpy as np

a = np.array([1,2.,'NTHU'])
print(a)

['1' '2.0' 'NTHU']


# dtype

In [39]:
import numpy as np

a = np.empty(3, dtype = int)           ; print(a)
a = np.zeros(3, dtype = int)           ; print(a)
a = np.ones(3, dtype = int)            ; print(a)
a = np.full(3, 2.2, dtype = int)       ; print(a)
a = np.full(3, 2, dtype = float)       ; print(a)
a = np.arange(3, dtype = float)        ; print(a)
a = np.array([0, 1, 2], dtype = float) ; print(a)

[                  0 4607182418800017408 4611686018427387904]
[0 0 0]
[1 1 1]
[2 2 2]
[2. 2. 2.]
[0. 1. 2.]
[0. 1. 2.]


# N-dimension Array

In [48]:
import numpy as np

a = np.empty((3,3))                             ; print("empty:\n", a)
a = np.zeros((3,3))                             ; print("zeros:\n", a)
a = np.ones((3,3))                              ; print("ones:\n", a)
a = np.full((3,3), 2)                           ; print("full:\n", a)
a = np.array([ [0, 1, 2],[3, 4, 5],[6, 7, 8] ]) ; print("array:\n", a)

empty:
 [[1.e-323 1.e-323 1.e-323]
 [1.e-323 1.e-323 1.e-323]
 [1.e-323 1.e-323 1.e-323]]
zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
ones:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
full:
 [[2 2 2]
 [2 2 2]
 [2 2 2]]
array:
 [[0 1 2]
 [4 5 6]
 [7 8 9]]


In [63]:
a = np.array([ [0, 1, 2],[3, 4, 5],[6, 7, 8] ])            ; print("array:\n", a)
a = np.array([ [0, 1, 2, 3, 4, 5, 6, 7, 8] ]).reshape(3,3) ; print("array:\n", a)
a = np.arange(9).reshape(3,3)                              ; print("array:\n", a)

array:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
array:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
array:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


# Get value

In [62]:
a = np.array([ [0, 1, 2],[3, 4, 5],[6, 7, 8] ])
print(a[1,1])
print(a[1][1])

4
4


In [67]:
a = np.array([ [0, 1, 2],[3, 4, 5],[6, 7, 8] ])
print(a[1],type(a[1]))


[3 4 5] <class 'numpy.ndarray'>


# reshape

In [71]:
a = np.arange(6)   ; print("array:\n", a, 'shape =', a.shape)
a = a.reshape(2,3) ; print("array:\n", a, 'shape =', a.shape)
a = a.reshape(3,2) ; print("array:\n", a, 'shape =', a.shape)

array:
 [0 1 2 3 4 5] shape = (6,)
array:
 [[0 1 2]
 [3 4 5]] shape = (2, 3)
array:
 [[0 1]
 [2 3]
 [4 5]] shape = (3, 2)


In [97]:
#1-Dimension
a = np.arange(6)              ; print(a, ', shape =', a.shape)
#2-Dimension
a = np.arange(6).reshape(1,6) ; print(a, ', shape =', a.shape)
a = np.arange(6).reshape(6,1) ; print(a, ', shape =', a.shape)

[0 1 2 3 4 5] , shape = (6,)
[[0 1 2 3 4 5]] , shape = (1, 6)
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]] , shape = (6, 1)


# Index

In [ ]:
a = np.array([[0, 0, 0], [0, 1, 0], [0, 0, 2]])
a[1, 1] ; print(a)
a[2, 1] ; print(a)
a[1]    ; print(a)

# Slice

In [105]:
a = np.arange(25).reshape(5,5)
print(a[0, 2:4])
print(a[3:, 3:])
print(a[:, 1])
print(a[2::2, ::2])

[2 3]
[[18 19]
 [23 24]]
[ 1  6 11 16 21]
[[10 12 14]
 [20 22 24]]


# Matrix-Scalar Operations

In [78]:
a = np.arange(9).reshape(3,3)
b = a + 1   ; print(b)
c = a * 2   ; print(c)
d = a ** 2  ; print(d)
e = 2 ** a  ; print(e)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]]
[[ 0  1  4]
 [ 9 16 25]
 [36 49 64]]
[[  1   2   4]
 [  8  16  32]
 [ 64 128 256]]


# Matrix-Matrix Operations

In [ ]:
a = np.arange(9).reshape(3,3)
b = np.ones(9).reshape(3,3)+1

print(a – b)
print(a * b)
print(a @ b)