# Sequence vs. Numpy Array

In [1]:
import numpy as np

x = [0, 1, 2]*2            ; print(x)
x = np.array([0, 1, 2])*2 ; print(x)

[0, 1, 2, 0, 1, 2]
[0 2 4]


# Array Creation 

In [2]:
import numpy as np

a = np.empty(3)         ; print(a)
a = np.zeros(3)         ; print(a)
a = np.ones(3)          ; print(a)
a = np.full(3, 2.2)     ; print(a)
a = np.full(3, 2)       ; print(a)
a = np.arange(3)        ; print(a)
a = np.array([0, 1, 2]) ; print(a)

[0.e+000 5.e-324 1.e-323]
[0. 0. 0.]
[1. 1. 1.]
[2.2 2.2 2.2]
[2 2 2]
[0 1 2]
[0 1 2]


# Same Data Type

In [3]:
import numpy as np

a = np.empty(3)
print(a)
a[0] = int(1)
print(a)

[0.e+000 5.e-324 1.e-323]
[1.e+000 5.e-324 1.e-323]


In [4]:
import numpy as np

a = np.array([1,2.,'NTHU'])
print(a)

['1' '2.0' 'NTHU']


# dtype

In [5]:
import numpy as np

a = np.empty(3, dtype = int)           ; print(a)
a = np.zeros(3, dtype = int)           ; print(a)
a = np.ones(3, dtype = int)            ; print(a)
a = np.full(3, 2.2, dtype = int)       ; print(a)
a = np.full(3, 2, dtype = float)       ; print(a)
a = np.arange(3, dtype = float)        ; print(a)
a = np.array([0, 1, 2], dtype = float) ; print(a)

[4607182418800017408                   1                   2]
[0 0 0]
[1 1 1]
[2 2 2]
[2. 2. 2.]
[0. 1. 2.]
[0. 1. 2.]


# N-dimension Array

In [6]:
import numpy as np

a = np.empty((3,3))                             ; print("empty:\n", a)
a = np.zeros((3,3))                             ; print("zeros:\n", a)
a = np.ones((3,3))                              ; print("ones:\n", a)
a = np.full((3,3), 2)                           ; print("full:\n", a)
a = np.array([ [0, 1, 2],[3, 4, 5],[6, 7, 8] ]) ; print("array:\n", a)

empty:
 [[4.4e-323 0.0e+000 0.0e+000]
 [0.0e+000 0.0e+000 0.0e+000]
 [0.0e+000 0.0e+000 0.0e+000]]
zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
ones:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
full:
 [[2 2 2]
 [2 2 2]
 [2 2 2]]
array:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


In [7]:
import numpy as np

a = np.array([ [0, 1, 2],[3, 4, 5],[6, 7, 8] ])            ; print("array:\n", a)
a = np.array([ [0, 1, 2, 3, 4, 5, 6, 7, 8] ]).reshape(3,3) ; print("array:\n", a)
a = np.arange(9).reshape(3,3)                              ; print("array:\n", a)

array:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
array:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
array:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


In [8]:
import numpy as np

a = np.array([ [0, 1, 2],[3, 4, 5],[6, 7, 8] ])
print(a[1],type(a[1]))

[3 4 5] <class 'numpy.ndarray'>


# reshape

In [9]:
import numpy as np

a = np.arange(6)   ; print("array:\n", a, 'shape =', a.shape)
a = a.reshape(2,3) ; print("array:\n", a, 'shape =', a.shape)
a = a.reshape(3,2) ; print("array:\n", a, 'shape =', a.shape)

array:
 [0 1 2 3 4 5] shape = (6,)
array:
 [[0 1 2]
 [3 4 5]] shape = (2, 3)
array:
 [[0 1]
 [2 3]
 [4 5]] shape = (3, 2)


In [10]:
import numpy as np

#1-Dimension
a = np.arange(6)              ; print(a, ', shape =', a.shape)
#2-Dimension
a = np.arange(6).reshape(1,6) ; print(a, ', shape =', a.shape)
a = np.arange(6).reshape(6,1) ; print(a, ', shape =', a.shape)

[0 1 2 3 4 5] , shape = (6,)
[[0 1 2 3 4 5]] , shape = (1, 6)
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]] , shape = (6, 1)


# Get value

In [11]:
import numpy as np

a = np.arange(9).reshape(3,3)
print(a)
print(a[1:], a[1:].shape)
print(a[1:][1], a[1:][1].shape) 
print(a[1:,1], a[1:,1].shape)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[3 4 5]
 [6 7 8]] (2, 3)
[6 7 8] (3,)
[4 7] (2,)


# Index

In [12]:
import numpy as np

a = np.array([[0, 0, 0], [0, 1, 0], [0, 0, 2]])
print(a[1, 1])
a[2, 1] = 10 ; print(a)
print(a[1])

1
[[ 0  0  0]
 [ 0  1  0]
 [ 0 10  2]]
[0 1 0]


# Slice

In [13]:
import numpy as np

a = np.arange(25).reshape(5,5)
print(a[0, 2:4])
print(a[3:, 3:])
print(a[:, 1])
print(a[2::2, ::2])

[2 3]
[[18 19]
 [23 24]]
[ 1  6 11 16 21]
[[10 12 14]
 [20 22 24]]


# Comparisons

In [14]:
import numpy as np

a = np.array([1, 2, 3, 4]) 
b = np.array([4, 2, 2, 4]) 
print(a == b) # => [False True False True]
print(a > b) # => [False False True False]

[False  True False  True]
[False False  True False]


# Sum

In [15]:
import numpy as np

x = np.array([ [1, 2, 3, 4] ]) 
print(np.sum(x)) # => 10 
x = np.array([ [1, 1], [2, 2] ]) 
print(x.sum(axis=0)) # columns (first dimension) [3 3]
print(x[:, 0].sum(), x[:, 1].sum()) # => 3 3 
print(x.sum(axis=1)) # rows (second dimension) [2 4] 
print(x[0, :].sum(), x[1, :].sum()) # => 2 4

10
[3 3]
3 3
[2 4]
2 4


# Statistics

In [16]:
import numpy as np

x = np.array([1, 2, 3, 1])
print(x.mean()) # => 1.75 
print(np.median(x)) # => 1.5
print(x.std()) # => 0.82915619758885

1.75
1.5
0.82915619758885


# Extrema

In [17]:
import numpy as np

x = np.array([1, 3, 2]) 
print(x.min()) # => 1 
print(x.max()) # => 3

1
3


# Transpose and Inverse 

In [18]:
import numpy as np

A = np.array([ [1, 2, 3], [4, 5, 6], [7, 8, 9] ])
AT = A.T
print(AT)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [19]:
import numpy as np

A = np.array([ [1, 2], [3, 4] ])
Ainv = np.linalg.inv(A)
print(Ainv)

[[-2.   1. ]
 [ 1.5 -0.5]]


# Matrix-Scalar Operations

In [20]:
import numpy as np

a = np.arange(9).reshape(3,3) ;print(a)
b = a + 1                     ;print(b)
c = a * 2                     ;print(c)
d = a ** 2                    ;print(d)
e = 2 ** a                    ;print(e)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]]
[[ 0  1  4]
 [ 9 16 25]
 [36 49 64]]
[[  1   2   4]
 [  8  16  32]
 [ 64 128 256]]


# Matrix-Matrix Operations

In [21]:
import numpy as np

a = np.arange(9).reshape(3,3)
b = np.ones(9).reshape(3,3)+1

print(a - b)
print(a * b)
print(a @ b)

[[-2. -1.  0.]
 [ 1.  2.  3.]
 [ 4.  5.  6.]]
[[ 0.  2.  4.]
 [ 6.  8. 10.]
 [12. 14. 16.]]
[[ 6.  6.  6.]
 [24. 24. 24.]
 [42. 42. 42.]]


# Practice

In [22]:
import numpy as np
'''
2x+3y=21
4x+2y=22
''' 
A = np.array([[2,3],[4,2]])
B = np.array([21,22]).reshape(2,1)
a = A[0,0]
b = A[0,1]
c = A[1,0]
d = A[1,1]
invA = [ [d,-b], [-c,d] ] / (a*d-b*c)
X = invA @ B ; print(X)

[[3.]
 [5.]]


In [23]:
import numpy as np

A = np.array([[2,3],[4,2]])
B = np.array([ [21,22] ]).T
X = np.linalg.inv(A) @ B; print(X)

[[3.]
 [5.]]
