# Integer-valued random

In [151]:
import random 

print(random.randint(0,1))

0


In [92]:
import random 

print( random.randrange(2) )
print( random.randrange(2,6,2) )
print( random.randint(0,1) )

1
2
1


# Real-valued random

In [82]:
import random 

print( random.random() ) #[0.0, 1.0)
print( random.uniform(1, 2) ) #Return a random floating point number N such that a <= N <= b for a <= b and b <= N <= a for b < a

0.6158454302342216
1.5406951305427263


# Functions for sequences

In [140]:
sample = ['1', '2', '3', '4', '5']

print(random.choice(sample))
print( random.choices(sample, k=3) ) 
print( random.sample(sample, k=3) )

2
['4', '4', '1']
['3', '1', '2']


In [124]:
sample = ['1', '2', '3', '4', '5']

random.shuffle(sample)
print(sample)

['5', '2', '4', '1', '3']


# Functions for Numpy

In [144]:
import numpy as np

'''random integers'''
print( np.random.randint(5, size=3) )
print( np.random.randint(3, 5, size=3) )
print( np.random.randint(5, size=(2, 4)) )

'''Random [0, 1) in a given shape'''
print( np.random.rand() )
print( np.random.rand(2,1) )


[1 1 1]
[3 4 4]
[[2 3 1 4]
 [4 3 0 3]]
0.7931028821350796
[[0.82177856]
 [0.48189158]]
