# Integer-valued random

In [1]:
import random 

print(random.randint(0, 1))

0


In [2]:
import random 

print( random.randrange(2) )
print( random.randrange(2, 6, 2) )
print( random.randint(0, 1) )

1
4
1


# Real-valued random

In [3]:
import random 

print( random.random() ) #[0.0, 1.0)
print( random.uniform(1, 2) ) #Return a random floating point number N such that a <= N <= b for a <= b and b <= N <= a for b < a

0.5611313859480428
1.2942975354952666


# Functions for sequences

In [4]:
sample = ['1', '2', '3', '4', '5']

print(random.choice(sample))
print( random.choices(sample, k=3) ) 
print( random.sample(sample, k=3) )

5
['3', '2', '2']
['4', '3', '5']


In [5]:
sample = ['1', '2', '3', '4', '5']

random.shuffle(sample)
print(sample)

['1', '3', '4', '5', '2']


# Functions for Numpy

In [6]:
import numpy as np

'''random integers'''
print( np.random.randint(5, size=3) )
print( np.random.randint(3, 5, size=3) )
print( np.random.randint(5, size=(2, 4)) )

'''Random [0, 1) in a given shape'''
print( np.random.rand() )
print( np.random.rand(2,1) )

[0 0 3]
[3 4 4]
[[3 3 2 1]
 [4 0 1 3]]
0.635247828250217
[[0.51073119]
 [0.00893411]]


In [7]:
import numpy as np

a = np.arange(10)
np.random.shuffle(a)
print(a) # => [1 7 5 2 9 4 3 6 0 8]

a = np.arange(9).reshape((3, 3))
np.random.shuffle(a)
print(a) # => array([[3, 4, 5], [6, 7, 8], [0, 1, 2]])

[0 8 3 2 7 6 1 4 9 5]
[[6 7 8]
 [0 1 2]
 [3 4 5]]
